# -*- coding: utf-8 -*-
"""Experiment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7M1RyBTP1CIRSgxz_oJ4_iioEESCvOD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


# 1. Helper: load and preprocess dataset

def load_dataset(path):
    df = pd.read_csv(path)

    print(f"\nLoading: {path}")
    print("Original shape:", df.shape)

    df[" Label"] = df[" Label"].str.strip()
    df = df.replace([np.inf, -np.inf], np.nan)
    df = df.dropna()

    print("Shape after cleaning:", df.shape)

    df["target"] = (df[" Label"] != "BENIGN").astype(int)

    X = df.drop(columns=[" Label", "target"])
    X = X.select_dtypes(include=["number"])
    y = df["target"]

    return X, y



# 2. Load both datasets

path_friday = "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"
path_thursday = "Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv"

X_friday, y_friday = load_dataset(path_friday)
X_thursday, y_thursday = load_dataset(path_thursday)

print("\nFriday feature count:", X_friday.shape[1])
print("Thursday feature count:", X_thursday.shape[1])

# 3. Align columns between datasets

common_columns = sorted(list(set(X_friday.columns).intersection(set(X_thursday.columns))))

X_friday = X_friday[common_columns].copy()
X_thursday = X_thursday[common_columns].copy()

print("Common feature count:", len(common_columns))


# 4. Split both datasets

Xf_train, Xf_test, yf_train, yf_test = train_test_split(
    X_friday, y_friday,
    test_size=0.3,
    random_state=42,
    stratify=y_friday
)

Xt_train, Xt_test, yt_train, yt_test = train_test_split(
    X_thursday, y_thursday,
    test_size=0.3,
    random_state=42,
    stratify=y_thursday
)

print("\nFriday split:")
print("Xf_train:", Xf_train.shape)
print("Xf_test:", Xf_test.shape)
print("yf_train distribution:\n", yf_train.value_counts())
print("yf_test distribution:\n", yf_test.value_counts())

print("\nThursday split:")
print("Xt_train:", Xt_train.shape)
print("Xt_test:", Xt_test.shape)
print("yt_train distribution:\n", yt_train.value_counts())
print("yt_test distribution:\n", yt_test.value_counts())


# 5. Train LR surrogate and target models

lr_surrogate_friday = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=1000, random_state=42)
)

lr_target_friday = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=1000, random_state=42)
)

lr_target_thursday = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=1000, random_state=42)
)

lr_surrogate_friday.fit(Xf_train, yf_train)
lr_target_friday.fit(Xf_train, yf_train)
lr_target_thursday.fit(Xt_train, yt_train)

print("\nModels trained successfully.")


# 6. Baseline evaluation

pred_friday_clean = lr_target_friday.predict(Xf_test)
pred_thursday_clean = lr_target_thursday.predict(Xt_test)

acc_friday_clean = accuracy_score(yf_test, pred_friday_clean)
acc_thursday_clean = accuracy_score(yt_test, pred_thursday_clean)

print("\nBaseline accuracy (Friday target on Friday test):", acc_friday_clean)
print("Baseline accuracy (Thursday target on Thursday test):", acc_thursday_clean)

print("\nFriday target classification report:")
print(classification_report(yf_test, pred_friday_clean))

print("\nThursday target classification report:")
print(classification_report(yt_test, pred_thursday_clean))


# 7. Generate adversarial samples from Friday surrogate

scaler = lr_surrogate_friday.named_steps["standardscaler"]
lr_model = lr_surrogate_friday.named_steps["logisticregression"]
weights = lr_model.coef_[0]

epsilons = [0.01, 0.05, 0.10]
results = []

# Friday adversarial samples (same-dataset case)
Xf_test_scaled = scaler.transform(Xf_test)

# Use Friday train bounds for clipping
x_min_f = Xf_train.min().values
x_max_f = Xf_train.max().values

# Thursday test also needs to be transformed using the Friday surrogate scaler
Xt_test_scaled_by_friday = scaler.transform(Xt_test)

for epsilon in epsilons:

    # Same dataset: Friday -> Friday

    Xf_adv_scaled = Xf_test_scaled + epsilon * np.sign(weights)
    Xf_adv = scaler.inverse_transform(Xf_adv_scaled)
    Xf_adv = np.clip(Xf_adv, x_min_f, x_max_f)
    Xf_adv_df = pd.DataFrame(Xf_adv, columns=Xf_test.columns, index=Xf_test.index)

    pred_friday_adv = lr_target_friday.predict(Xf_adv_df)

    adv_acc_friday = accuracy_score(yf_test, pred_friday_adv)
    malicious_idx_f = (yf_test == 1)
    evasion_rate_friday = np.mean(pred_friday_adv[malicious_idx_f] == 0)

    results.append({
        "surrogate_dataset": "Friday",
        "target_dataset": "Friday",
        "epsilon": epsilon,
        "clean_accuracy": acc_friday_clean,
        "adversarial_accuracy": adv_acc_friday,
        "accuracy_drop": acc_friday_clean - adv_acc_friday,
        "evasion_rate": evasion_rate_friday
    })


    # Different dataset: Friday -> Thursday

    Xt_adv_scaled = Xt_test_scaled_by_friday + epsilon * np.sign(weights)
    Xt_adv = scaler.inverse_transform(Xt_adv_scaled)

    # Clip using Friday bounds because perturbation is generated from Friday surrogate space
    Xt_adv = np.clip(Xt_adv, x_min_f, x_max_f)

    Xt_adv_df = pd.DataFrame(Xt_adv, columns=Xt_test.columns, index=Xt_test.index)

    pred_thursday_adv = lr_target_thursday.predict(Xt_adv_df)

    adv_acc_thursday = accuracy_score(yt_test, pred_thursday_adv)
    malicious_idx_t = (yt_test == 1)
    evasion_rate_thursday = np.mean(pred_thursday_adv[malicious_idx_t] == 0)

    results.append({
        "surrogate_dataset": "Friday",
        "target_dataset": "Thursday",
        "epsilon": epsilon,
        "clean_accuracy": acc_thursday_clean,
        "adversarial_accuracy": adv_acc_thursday,
        "accuracy_drop": acc_thursday_clean - adv_acc_thursday,
        "evasion_rate": evasion_rate_thursday
    })

results_df = pd.DataFrame(results)

print("\nExperiment 2 Results:")
print(results_df.round(4))


# 8. Plot adversarial accuracy

plt.figure(figsize=(8, 5))

for target_dataset in results_df["target_dataset"].unique():
    subset = results_df[results_df["target_dataset"] == target_dataset]
    plt.plot(
        subset["epsilon"],
        subset["adversarial_accuracy"],
        marker="o",
        label=f"Target: {target_dataset}"
    )

plt.xlabel("Epsilon")
plt.ylabel("Adversarial Accuracy")
plt.ylim(0, 1.05)
plt.title("Same vs Different Dataset")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


# 9. Plot evasion rate

plt.figure(figsize=(8, 5))

for target_dataset in results_df["target_dataset"].unique():
    subset = results_df[results_df["target_dataset"] == target_dataset]
    plt.plot(
        subset["epsilon"],
        subset["evasion_rate"],
        marker="o",
        label=f"Target: {target_dataset}"
    )

plt.xlabel("Epsilon")
plt.ylabel("Evasion Rate")
plt.ylim(0, 1.05)
plt.title("Evasion Rate (Same vs Different Dataset)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()