# -*- coding: utf-8 -*-
"""Experiment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16gDJhxjxAyRrL5IImX00Gc1XD2BDw_TS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score


# 1. Load and preprocess dataset

path = "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"
df = pd.read_csv(path)

print("Original shape:", df.shape)

df[" Label"] = df[" Label"].str.strip()
df = df.replace([np.inf, -np.inf], np.nan)
df = df.dropna()

print("Shape after cleaning:", df.shape)

df["target"] = (df[" Label"] != "BENIGN").astype(int)

X = df.drop(columns=[" Label", "target"])
X = X.select_dtypes(include=["number"])
y = df["target"]

# Fixed train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train distribution:\n", y_train.value_counts())
print("y_test distribution:\n", y_test.value_counts())

# 2. Train fixed target model on full training set

rf_target = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_target.fit(X_train, y_train)

rf_clean_pred = rf_target.predict(X_test)
rf_clean_acc = accuracy_score(y_test, rf_clean_pred)

print("\nRF target baseline accuracy:", rf_clean_acc)


# 3. Train LR surrogate with different training sizes

fractions = [0.10, 0.25, 0.50, 0.75, 1.00]
epsilons = [0.01, 0.05, 0.10]

results = []

for frac in fractions:
    # sample surrogate training subset from the fixed training set
    if frac < 1.0:
        X_sur, _, y_sur, _ = train_test_split(
            X_train, y_train,
            train_size=frac,
            random_state=42,
            stratify=y_train
        )
    else:
        X_sur = X_train.copy()
        y_sur = y_train.copy()

    print(f"\nTraining LR surrogate with {int(frac * 100)}% of training data")
    print("Surrogate train shape:", X_sur.shape)

    lr_surrogate = make_pipeline(
        StandardScaler(),
        LogisticRegression(max_iter=1000, random_state=42)
    )

    lr_surrogate.fit(X_sur, y_sur)

    # extract scaler and LR model
    scaler = lr_surrogate.named_steps["standardscaler"]
    lr_model = lr_surrogate.named_steps["logisticregression"]
    weights = lr_model.coef_[0]

    # transform full fixed test set using surrogate scaler
    X_test_scaled = scaler.transform(X_test)

    # clipping bounds based on surrogate training subset
    x_min = X_sur.min().values
    x_max = X_sur.max().values

    # optional: surrogate clean accuracy on fixed test set
    lr_clean_pred = lr_surrogate.predict(X_test)
    lr_clean_acc = accuracy_score(y_test, lr_clean_pred)

    for epsilon in epsilons:
        # generate adversarial samples from surrogate
        X_adv_scaled = X_test_scaled + epsilon * np.sign(weights)
        X_adv = scaler.inverse_transform(X_adv_scaled)
        X_adv = np.clip(X_adv, x_min, x_max)

        X_adv_df = pd.DataFrame(X_adv, columns=X_test.columns, index=X_test.index)

        # evaluate on target RF
        rf_adv_pred = rf_target.predict(X_adv_df)
        rf_adv_acc = accuracy_score(y_test, rf_adv_pred)

        # evasion rate on malicious samples
        malicious_idx = (y_test == 1)
        evasion_rate = np.mean(rf_adv_pred[malicious_idx] == 0)

        results.append({
            "surrogate_model": "LR",
            "target_model": "RF",
            "train_fraction": frac,
            "surrogate_train_size": len(X_sur),
            "epsilon": epsilon,
            "surrogate_clean_accuracy": lr_clean_acc,
            "target_clean_accuracy": rf_clean_acc,
            "target_adversarial_accuracy": rf_adv_acc,
            "accuracy_drop": rf_clean_acc - rf_adv_acc,
            "evasion_rate": evasion_rate
        })

results_df = pd.DataFrame(results)

print("\nExperiment 3 Results:")
print(results_df.round(4))


# 4. Plot adversarial accuracy vs training fraction

plt.figure(figsize=(8, 5))

for epsilon in results_df["epsilon"].unique():
    subset = results_df[results_df["epsilon"] == epsilon]
    plt.plot(
        subset["train_fraction"],
        subset["target_adversarial_accuracy"],
        marker="o",
        label=f"epsilon={epsilon}"
    )

plt.xlabel("Surrogate Training Fraction")
plt.ylabel("Target Adversarial Accuracy")
plt.ylim(0, 1.05)
plt.title("Effect of Surrogate Training Size on RF Accuracy")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


# 5. Plot evasion rate vs training fraction

plt.figure(figsize=(8, 5))

for epsilon in results_df["epsilon"].unique():
    subset = results_df[results_df["epsilon"] == epsilon]
    plt.plot(
        subset["train_fraction"],
        subset["evasion_rate"],
        marker="o",
        label=f"epsilon={epsilon}"
    )

plt.xlabel("Surrogate Training Fraction")
plt.ylabel("Evasion Rate")
plt.ylim(0, 1.05)
plt.title("Effect of Surrogate Training Size on Evasion Rate")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()