# -*- coding: utf-8 -*-
"""Experiment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w0mgVwb3T6Qh0FdSQdn7ATHnRIMTFInt
"""

import os

os.listdir()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report


# 1. Load and preprocess

path = "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"
df = pd.read_csv(path)

print("Original shape:", df.shape)

df[" Label"] = df[" Label"].str.strip()
df = df.replace([np.inf, -np.inf], np.nan)
df = df.dropna()

print("Shape after cleaning:", df.shape)

df["target"] = (df[" Label"] != "BENIGN").astype(int)

X = df.drop(columns=[" Label", "target"])
X = X.select_dtypes(include=["number"])
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train distribution:\n", y_train.value_counts())
print("y_test distribution:\n", y_test.value_counts())


# 2. Define models

lr = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=1000, random_state=42)
)

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

svm = make_pipeline(
    StandardScaler(),
    SVC(kernel="rbf", random_state=42)
)

knn = make_pipeline(
    StandardScaler(),
    KNeighborsClassifier(n_neighbors=5)
)

models = {
    "LR": lr,
    "RF": rf,
    "SVM": svm,
    "KNN": knn
}


# 3. Train models

for name, model in models.items():
    model.fit(X_train, y_train)

print("All models trained successfully.")


# 4. Baseline evaluation

baseline_results = []

for name, model in models.items():
    pred = model.predict(X_test)
    acc = accuracy_score(y_test, pred)

    baseline_results.append({
        "model": name,
        "baseline_accuracy": acc
    })

    print(f"\n{name} baseline accuracy: {acc:.4f}")
    print(classification_report(y_test, pred))

baseline_df = pd.DataFrame(baseline_results)
print("\nBaseline Results:")
print(baseline_df)


# 5. Generate adversarial samples from LR surrogate

scaler = lr.named_steps["standardscaler"]
lr_model = lr.named_steps["logisticregression"]
weights = lr_model.coef_[0]

epsilons = [0.01, 0.05, 0.10]
results = []

X_test_scaled = scaler.transform(X_test)

# Clip adversarial samples to training feature range
x_min = X_train.min().values
x_max = X_train.max().values

for epsilon in epsilons:
    # Create adversarial samples using LR surrogate
    X_adv_scaled = X_test_scaled + epsilon * np.sign(weights)
    X_adv = scaler.inverse_transform(X_adv_scaled)
    X_adv = np.clip(X_adv, x_min, x_max)

    X_adv_df = pd.DataFrame(X_adv, columns=X_test.columns, index=X_test.index)

    for name, model in models.items():
        clean_pred = model.predict(X_test)
        adv_pred = model.predict(X_adv_df)

        clean_acc = accuracy_score(y_test, clean_pred)
        adv_acc = accuracy_score(y_test, adv_pred)

        # Evasion rate: malicious samples misclassified as benign
        malicious_idx = (y_test == 1)
        evasion_rate = np.mean(adv_pred[malicious_idx] == 0)

        results.append({
            "surrogate": "LR",
            "target": name,
            "epsilon": epsilon,
            "clean_accuracy": clean_acc,
            "adversarial_accuracy": adv_acc,
            "accuracy_drop": clean_acc - adv_acc,
            "evasion_rate": evasion_rate
        })

results_df = pd.DataFrame(results)

print("\nAdversarial Results:")
print(results_df)


# 6. Plot adversarial accuracy vs epsilon

plt.figure(figsize=(8, 5))

for target in results_df["target"].unique():
    subset = results_df[results_df["target"] == target]
    plt.plot(
        subset["epsilon"],
        subset["adversarial_accuracy"],
        marker="o",
        label=target
    )

plt.xlabel("Epsilon")
plt.ylabel("Adversarial Accuracy")
plt.ylim(0, 1.05)
plt.title("Transferability of LR-based Adversarial Samples to Different Target Models")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


# 7. Plot evasion rate vs epsilon

plt.figure(figsize=(8, 5))

for target in results_df["target"].unique():
    subset = results_df[results_df["target"] == target]
    plt.plot(
        subset["epsilon"],
        subset["evasion_rate"],
        marker="o",
        label=target
    )

plt.xlabel("Epsilon")
plt.ylabel("Evasion Rate")
plt.ylim(0, 1.05)
plt.title("Evasion Rate of LR-based Adversarial Samples on Different Target Models")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


# 8. Optional: save results

results_df.to_csv("experiment1_results.csv", index=False)
print("\nResults saved to experiment1_results.csv")



# 9. Cross-model transferability plot (fixed epsilon)


fixed_epsilon = 0.05

subset = results_df[results_df["epsilon"] == fixed_epsilon].copy()

plt.figure(figsize=(8, 5))
plt.bar(subset["target"], subset["adversarial_accuracy"])
plt.xlabel("Target Model")
plt.ylabel("Adversarial Accuracy")
plt.ylim(0, 1.05)
plt.title(f"Cross-Model Transferability of LR-Based Adversarial Samples (epsilon={fixed_epsilon})")
plt.grid(axis="y")
plt.tight_layout()
plt.show()